// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MNKR_RandomTreasure","status":true,"description":"v1.0.1 ランダム宝箱プラグイン","parameters":{"itemName":"1","itemIcon":"2","itemLot":"3"}}
];
